a=int(input('enter the value '))
b=int(input('enter the value '))
difference=(a-b)
print(difference)
a=int(input('enter the value '))
b=int(input('enter the value '))
sum=(a+b)
print(sum)
a=int(input('enterthe value '))
b=int(input('enter thhe value '))
div=(a/b)
print(div)
a=int(input('enter the value '))
b=int(input('enter the value '))
mul=(a*b)
print(mul)